<?php
return [
    'GOOGLE_CLIENT_ID'     => $_ENV['GOOGLE_CLIENT_ID'] ?? '',
    'GOOGLE_CLIENT_SECRET' => $_ENV['GOOGLE_CLIENT_SECRET'] ?? '',
    'GOOGLE_REDIRECT_URI'  => $_ENV['GOOGLE_REDIRECT_URI'] ?? '',
    'OPENROUTER_API_KEY'   => $_ENV['OPENROUTER_API_KEY'] ?? '',
];


